### ISSUE TITLE
Update to Marko v4

### ISSUE THREAD

**Issue by StarpTech** [marko-js-samples/todomvc-marko#2]
Example of testing Single file components

**Comment by austinkelleher** [comment]
Addressed in: https://github.com/marko-js-samples/todomvc-marko/commit/ab8ee70ffc93f3abb0a734c3fe5db57f0f86aca3

**Comment by StarpTech** [comment]
@austinkelleher I can't see any test for single-file-component.

**Comment by austinkelleher** [comment]
@StarpTech Is this what you're looking for? https://github.com/marko-js-samples/todomvc-marko/blob/master/src/components/app-footer/index.marko

**Comment by austinkelleher** [comment]
Or do you mean like functional testing?

**Comment by StarpTech** [comment]
yes I mean a unit test.
